services:
  - docker

env:
  global:
    - DOCKER_IP=localhost
  matrix:
    - PHP_VERSION=5.5 IMAGE_FLAVOUR=apache
    - PHP_VERSION=5.6 IMAGE_FLAVOUR=apache
    - PHP_VERSION=7.0 IMAGE_FLAVOUR=apache
    - PHP_VERSION=7.1 IMAGE_FLAVOUR=apache
    - PHP_VERSION=7.2 IMAGE_FLAVOUR=apache
    - PHP_VERSION=7.3 IMAGE_FLAVOUR=apache
    - PHP_VERSION=5.5 IMAGE_FLAVOUR=cli
    - PHP_VERSION=5.6 IMAGE_FLAVOUR=cli
    - PHP_VERSION=7.0 IMAGE_FLAVOUR=cli
    - PHP_VERSION=7.1 IMAGE_FLAVOUR=cli
    - PHP_VERSION=7.2 IMAGE_FLAVOUR=cli
    - PHP_VERSION=7.3 IMAGE_FLAVOUR=cli
    - PHP_VERSION=5.5 IMAGE_FLAVOUR=fpm
    - PHP_VERSION=5.6 IMAGE_FLAVOUR=fpm
    - PHP_VERSION=7.0 IMAGE_FLAVOUR=fpm
    - PHP_VERSION=7.1 IMAGE_FLAVOUR=fpm
    - PHP_VERSION=7.2 IMAGE_FLAVOUR=fpm
    - PHP_VERSION=7.3 IMAGE_FLAVOUR=fpm

script:
  - travis_wait 20 bash test-runner.sh
